# Inserts a blank line between shell prompts
add_newline = false
format = """
[â”Œâ”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€](bold green)
[â”‚](bold green)$character$directory$character$git_branch$character$git_commit
[â””â”€>](bold green) """

[character] # The name of the module we are configuring is "character"
format = "ğŸŒŸğŸ§šğŸ„"
# format = "ğŸŒŸ "
# success_symbol = "ğŸŒ¸" 
# error_symbol = "ğŸ§š"
# vicmd_symbol = "ğŸ„"
# Disable the package module, hiding it from the prompt completely
[package]
disabled = true
[git_branch]
style = "#ff9999"
[directory]
style = "bright-green"
